### ISSUE TITLE
Persistent error in the log around sensor.pfsense_system_boottime starting with HA 2023.2.0b0

### ISSUE THREAD

**Issue by rccoleman** [travisghansen/hass-pfsense#136]
After installing 2023.2.0b0 today, my HA log is being flooded with the following error & backtrace:

```
2023-01-25 16:08:58.176 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 482, in state
    raise ValueError(
ValueError: Sensor sensor.pfsense_system_boottime has a unit of measurement and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp
```

I suspect that they just started cracking down on these discrepancies and it should be a straightforward fix.

**Comment by firstof9** [comment]
In the meantime, I've deleted the sensor from HA since it states that "the integration is no longer supplying this entity" or what ever to stop the log spam.

**Comment by travisghansen** [comment]
https://github.com/travisghansen/hass-pfsense/commit/978db5ea46f6d4b3ab2ae8995a0ad35ae7818133

Try `v0.5.12`.

**Comment by rccoleman** [comment]
I'm now getting tons of these:

```
2023-01-29 18:34:57.328 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.pfsense_gateway_expressvpn_vpnv4_loss has device class None, state class None and unit % thus indicating it has a numeric value; however, it has the non-numeric value:  (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by travisghansen** [comment]
Try `v0.5.13`.

**Comment by rccoleman** [comment]
Now:
```
2023-01-29 19:09:58.956 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 463, in state
    value = self.native_value
  File "/config/custom_components/pfsense/sensor.py", line 618, in native_value
    value = float(value)
ValueError: could not convert string to float: ''
```

**Comment by travisghansen** [comment]
Good hell lol. `v0.5.14`

**Comment by rccoleman** [comment]
Now back to the issue [here](https://github.com/travisghansen/hass-pfsense/issues/136#issuecomment-1407903855).

```
2023-01-29 19:17:22.042 INFO (MainThread) [homeassistant.components.update] Setting up update.pfsense
2023-01-29 19:17:22.122 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.pfsense_gateway_expressvpn_vpnv4_delay has device class None, state class None and unit ms thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-01-29 19:17:22.125 WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.pfsense_gateway_expressvpn_vpnv4_loss has device class None, state class None and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by travisghansen** [comment]
Sheesh. It's probably because when the data is empty I report it as unknown but perhaps should flag the entity as unavailable instead.

**Comment by travisghansen** [comment]
Can you apply this patch (I prefer not to keep doing releases until it's settled a bit)?

```
diff --git a/custom_components/pfsense/sensor.py b/custom_components/pfsense/sensor.py
index 2ddbcc2..8f6da99 100644
--- a/custom_components/pfsense/sensor.py
+++ b/custom_components/pfsense/sensor.py
@@ -580,6 +580,13 @@ class PfSenseGatewaySensor(PfSenseSensor):
         if gateway is None or property not in gateway.keys():
             return False
 
+        if property in ["stddev", "delay", "loss"]:
+            value = gateway[property]
+            if isinstance(value, str):
+                value = re.sub("[^0-9\.]*", "", value)
+                if len(value) < 1:
+                    return False
+
```

**Comment by rccoleman** [comment]
Your file appears to be different from mine and `patch` initially applied the patch to the wrong location, but I just fixed it.  I don't see any incorrect logs anymore with that patch.

**Comment by travisghansen** [comment]
OK, try `v0.5.15`

**Comment by rccoleman** [comment]
No issues with 0.5.15.  Thanks!
