### ISSUE TITLE
pfSense stopped to work

### ISSUE THREAD

**Issue by redskinhu** [travisghansen/hass-pfsense#166]
Hello

My pfSense stopped to work. Error on the integrations page: **Not loaded**

 I tried to reinstall but it, I can't remove the pfSense.

Home Assistant 2023.6.3
Supervisor 2023.06.2
Frontend 20230608.0 - latest

```
This error originated from a custom integration.
Logger: aiohttp.server
Source: custom_components/pfsense/__init__.py:23
Integration: pfsense (documentation, issues)
First occurred: 27 June 2023 at 19:19:34 (2 occurrences)
Last logged: 27 June 2023 at 19:19:54

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 87, in delete
    result = await hass.config_entries.async_remove(entry_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1072, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 578, in async_remove
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/pfsense/__init__.py", line 23, in <module>
    from homeassistant.helpers.entity_registry import async_get_registry
ImportError: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 27 June 2023 at 19:19:44 (1 occurrences)
Last logged: 27 June 2023 at 19:19:44

Error occurred loading flow for integration pfsense: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

**Comment by zaxbux** [comment]
The deprecated `async_get_registry` method was removed (https://github.com/home-assistant/core/pull/91928) in HA 2023.5, you need to update the integration to [v0.6.1](https://github.com/travisghansen/hass-pfsense/releases/tag/v0.6.1).

**Comment by khisanthax** [comment]
Hello,

I'm currently having the same error:

This error originated from a custom integration.

Logger: custom_components.pfsense.config_flow
Source: custom_components/pfsense/config_flow.py:147
Integration: pfSense (documentation, issues)
First occurred: September 2, 2023 at 6:37:16 AM (12 occurrences)
Last logged: 6:51:23 AM

Unexpected err=OSError(113, 'Host is unreachable'), type(err)=<class 'OSError'>

I am currently on v0.6.1 and HASS 2023.8.  Is there a way to resolve this?

**Comment by travisghansen** [comment]
Usually that error has nothing to do with the integration and represents some deeper networking issue :(

**Comment by khisanthax** [comment]
The only change I made to HA was add interfaces through proxmox with vlan tags.  Could that do it?

Other than that pfsense remains accessible as always.

**Comment by travisghansen** [comment]
It could be yeah.

**Comment by jeanpaulrh** [comment]
> The deprecated `async_get_registry` method was removed ([home-assistant/core#91928](https://github.com/home-assistant/core/pull/91928)) in HA 2023.5, you need to update the integration to [v0.6.1](https://github.com/travisghansen/hass-pfsense/releases/tag/v0.6.1).

Hi, and sorry for the dumb question. I updated HA (docker install) and HACS and PfSense integration stopped working with the async_get_registry error.
I updated HACS with wget and bash script, but PfSense integration is not updating and still doesn't work. Is there a way to force the update to the latest version?
Thanks.
