### ISSUE TITLE
XMLRPC errors - initial installation 

### ISSUE THREAD

**Issue by hockey6611** [travisghansen/hass-pfsense#35]
Thanks for this exciting new integration! I am having an issue upon my initial set up the integration I wanted to report. I am installing via HACS default, release v0.1.0, Home Assistant 2021.11.3, pfsense 2.5.2-RELEASE

I followed the readme guide, created a user in pfsense with "System - HA node sync" privileges, configured the integration in the HA integration flow. After confirming success, I'm immediately presented with the below error. I attemted to connect via domain/IP, and verify/not verify SSL; but received the same error each time.

I was able to find a related error on another repository of yours [here](https://github.com/travisghansen/kubernetes-pfsense-controller/issues/1). Unfortunately I wasn't able to discern anything useful here.

Do you have any recommendations or suggestions for troubleshooting this error?

Here is the integration page:
![image](https://user-images.githubusercontent.com/28613898/141666352-aff9ad8f-24c4-4271-a62c-1ee10e521313.png)

Here are the log entries associated with the error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:335
First occurred: 9:54:38 PM (5 occurrences)
Last logged: 10:23:21 PM

Config entry 'pfsenseha' for pfsense integration not ready yet: <Fault 1: "Unhandled XML_RPC2_InvalidTypeEncodeException exception:Impossible to encode value '' from type 'NULL'. No analogous type in XML_RPC.#0 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value::createFromNative(NULL)\n#1 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Response.php(86): XML_RPC2_Backend_Php_Value_Struct->encode()\n#4 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Backend_Php_Response::encode(Object(XML_RPC2_Backend_Php_Value_Struct), 'utf-8')\n#5 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()\n#6 /usr/local/www/xmlrpc.php(954): XML_RPC2_Backend_Php_Server->handleCall()\n#7 {main}">; Retrying in background
```

```
This error originated from a custom integration.

Logger: custom_components.pfsense
Source: custom_components/pfsense/pypfsense/__init__.py:78
Integration: pfSense (documentation, issues)
First occurred: 9:54:38 PM (40 occurrences)
Last logged: 10:34:25 PM

Unexpected error fetching pfseneha pfSense state data: <Fault 1: "Unhandled XML_RPC2_InvalidTypeEncodeException exception:Impossible to encode value '' from type 'NULL'. No analogous type in XML_RPC.#0 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value::createFromNative(NULL)\n#1 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Response.php(86): XML_RPC2_Backend_Php_Value_Struct->encode()\n#4 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Backend_Php_Response::encode(Object(XML_RPC2_Backend_Php_Value_Struct), 'utf-8')\n#5 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()\n#6 /usr/local/www/xmlrpc.php(954): XML_RPC2_Backend_Php_Server->handleCall()\n#7 {main}">
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/pfsense/__init__.py", line 94, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense/__init__.py", line 94, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
  File "/config/custom_components/pfsense/__init__.py", line 248, in update
    self._state["telemetry"] = self._get_telemetry()
  File "/config/custom_components/pfsense/__init__.py", line 224, in _get_telemetry
    return self._client.get_telemetry()
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 776, in get_telemetry
    data = self._exec_php(script)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 58, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 78, in _exec_php
    return self._get_proxy().pfsense.exec_php(script)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "Unhandled XML_RPC2_InvalidTypeEncodeException exception:Impossible to encode value '' from type 'NULL'. No analogous type in XML_RPC.#0 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value::createFromNative(NULL)\n#1 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Response.php(86): XML_RPC2_Backend_Php_Value_Struct->encode()\n#4 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Backend_Php_Response::encode(Object(XML_RPC2_Backend_Php_Value_Struct), 'utf-8')\n#5 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()\n#6 /usr/local/www/xmlrpc.php(954): XML_RPC2_Backend_Php_Server->handleCall()\n#7 {main}">
```

**Comment by travisghansen** [comment]
Welcome! This one may be tricky to hunt down if indeed it's the same issue :( It's clear something is coming back as a `NULL` php value but I'm not sure what which makes it hard to track down. Let me see if I can come up with some code that will clean that up.

**Comment by travisghansen** [comment]
Anything abnormal about your setup? Do you not have any gateways by chance?

**Comment by travisghansen** [comment]
OK, I have a feeling we're kicking the issue further down the road but I just committed a change to `main` that should help us get further along. Please switch to that branch and let me know what you get.

**Comment by hockey6611** [comment]
Thank you for the quick support! I switched to the `main` branch and my errors went away!

> Anything abnormal about your setup? Do you not have any gateways by chance?

Depends on what you mean by abnormal, I definitely have customizations above the standard WAN/LAN, but nothing  customized outside of the GUI. Here are my gateways. I have the WAN ipv6 disabled, could that cause the `NULL`?

![image](https://user-images.githubusercontent.com/28613898/141684050-cb2aff15-1916-4342-9649-8b4c9015342e.png)

**Comment by travisghansen** [comment]
No idea honestly. If an entity isn’t blowing up showing a value of unknown then it’s a field somewhere that doesn’t matter at all :)

The way I fixed it will resolve the issue entirely across the board.

**Comment by hockey6611** [comment]
Great, yeah sounds good. It does seem to be working just fine so far. Thanks! will you plan to put that in a next release? Or should I stay on the main channel?

**Comment by travisghansen** [comment]
I’ll probably snap a new release in the next couple days.
