### ISSUE TITLE
Fresh install XMLRPC error

### ISSUE THREAD

**Issue by wkearney99** [travisghansen/hass-pfsense#37]
2.5.2 release of pfsense.  Nothing special, just LAN/WAN.

Seeing this error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:335
First occurred: 7:40:10 AM (26 occurrences)
Last logged: 8:25:07 PM

Config entry 'pfsense' for pfsense integration not ready yet: <Fault 1: "Unhandled XML_RPC2_InvalidTypeEncodeException exception:Impossible to encode value '' from type 'NULL'. No analogous type in XML_RPC.#0 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value::createFromNative(NULL)\n#1 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Array.php(99): XML_RPC2_Backend_Php_Value_Struct->encode()\n#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Array->encode()\n#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#4 /usr/local/share/pear/XML/RPC2/Backend/Php/Response.php(86): XML_RPC2_Backend_Php_Value_Struct->encode()\n#5 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Backend_Php_Response::encode(Object(XML_RPC2_Backend_Php_Value_Struct), 'utf-8')\n#6 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()\n#7 /usr/local/www/xmlrpc.php(954): XML_RPC2_Backend_Php_Server->handleCall()\n#8 {main}">; Retrying in background
Config entry 'router' for pfsense integration not ready yet: <Fault 1: "Unhandled XML_RPC2_InvalidTypeEncodeException exception:Impossible to encode value '' from type 'NULL'. No analogous type in XML_RPC.#0 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value::createFromNative(NULL)\n#1 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Array.php(99): XML_RPC2_Backend_Php_Value_Struct->encode()\n#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Array->encode()\n#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Value/Struct.php(107): XML_RPC2_Backend_Php_Value_Struct->encode()\n#4 /usr/local/share/pear/XML/RPC2/Backend/Php/Response.php(86): XML_RPC2_Backend_Php_Value_Struct->encode()\n#5 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Backend_Php_Response::encode(Object(XML_RPC2_Backend_Php_Value_Struct), 'utf-8')\n#6 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()\n#7 /usr/local/www/xmlrpc.php(954): XML_RPC2_Backend_Php_Server->handleCall()\n#8 {main}">; Retrying in background
Config entry 'router' for pfsense integration not ready yet; Retrying in background

```

Tried using a different user, with the proper permissions set (basically, all of them) and no change.

logging on the router seems to think something's hitting the xmlrpc URL pretty hard:
```
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:13	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:13 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:14	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:14 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:14	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:14 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:14	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:14 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:14	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:14 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"
Nov 18 20:33:14	nginx		192.168.12.199 - wkearney [18/Nov/2021:20:33:14 -0500] "POST /xmlrpc.php HTTP/1.1" 200 160 "-" "Python-xmlrpc/3.9"

```

I'm willing to debug further, just tell me what to tweak.  I'm new to using HA, so bear with me if I don't know the ins/outs of troubleshooting with it.

**Comment by travisghansen** [comment]
Pretty sure I have a fix for this already in main. Can you switch to that instead of the tagged release and let me know what you get?

**Comment by wkearney99** [comment]
Yes, it took me a second to figure out HOW to change the release!  HACS->Integrations->pfsense->... menu->Re-download and only in THERE can you drop down on the version to change it.  

Changing it from 0.1.0 to 'main' seems to have eliminated this problem.  Yay!

**Comment by travisghansen** [comment]
Great! I’ll get a new release snapped soon so you don’t have to track main if you do not wish to do so.

**Comment by wkearney99** [comment]
Honestly, I know next to nothing about how HA, HACS and various releases, tags and the like are all stitched together.  I mean, I get the overall idea, but not how HA/HACS handle it.

So I'll defer to whatever suggestion you have for this.  Thanks!
