### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by thrawnarn** [travisghansen/hass-pfsense#42]
I can't get it to work and I really don't know how to get any more logging to be able to solve it. Could you point me to any direction or do you know what is wrong?

I'm running pfSense 2.5.2.
This is the only thing I can see in my logs.

```
2021-11-22 21:48:45 ERROR (MainThread) [custom_components.pfsense] Unexpected error fetching router pfSense state data: syntax error: line 2, column 0
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/pfsense/__init__.py", line 94, in async_update_data
await hass.async_add_executor_job(lambda: data.update())
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/pfsense/__init__.py", line 94, in <lambda>
await hass.async_add_executor_job(lambda: data.update())
File "/config/custom_components/pfsense/__init__.py", line 248, in update
self._state["telemetry"] = self._get_telemetry()
File "/config/custom_components/pfsense/__init__.py", line 224, in _get_telemetry
return self._client.get_telemetry()
File "/config/custom_components/pfsense/pypfsense/__init__.py", line 776, in get_telemetry
data = self._exec_php(script)
File "/config/custom_components/pfsense/pypfsense/__init__.py", line 58, in inner
response = func(*args, **kwargs)
File "/config/custom_components/pfsense/pypfsense/__init__.py", line 78, in _exec_php
return self._get_proxy().pfsense.exec_php(script)
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
return self.__send(self.__name, args)
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
response = self.__transport.request(
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
return self.parse_response(resp)
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1342, in parse_response
p.feed(data)
File "/usr/local/lib/python3.9/xmlrpc/client.py", line 445, in feed
self._parser.Parse(data, False)
xml.parsers.expat.ExpatError: syntax error: line 2, column 0
2021-11-22 21:48:45 DEBUG (MainThread) [custom_components.pfsense] Finished fetching router pfSense state data in 1.062 seconds (success: False)
```

**Comment by travisghansen** [comment]
This is after configuration succeeds?

**Comment by thrawnarn** [comment]
Yes

**Comment by travisghansen** [comment]
If you login to the pfsense ui I’m guessing you will see a ‘crash report’ or similar. It may show up on the main dashboard or be an entry in the alert system (little bell in the upper right).

Please check if indeed that is the case and if so send over whatever details you can gather.

**Comment by thrawnarn** [comment]
Ah, thats why I got that error. This is the error (repeated in 25mb log)

```
[22-Nov-2021 22:25:11 Europe/Stockholm] PHP Warning:  Use of undefined constant ifdescr - assumed 'ifdescr' (this will throw an Error in a future version of PHP) in /usr/local/www/xmlrpc.php(147) : eval()'d code on line 118
[22-Nov-2021 22:25:11 Europe/Stockholm] PHP Warning:  Cannot modify header information - headers already sent by (output started at /usr/local/www/xmlrpc.php(147) : eval()'d code:118) in /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php on line 100
[22-Nov-2021 22:25:11 Europe/Stockholm] PHP Warning:  Cannot modify header information - headers already sent by (output started at /usr/local/www/xmlrpc.php(147) : eval()'d code:118) in /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php on line 101
```

**Comment by travisghansen** [comment]
Oh, I'm pretty sure that was fixed, what version are you running?

**Comment by thrawnarn** [comment]
Gah, that were the issue. I was running 2.5.2 Beta (I was running beta becaude of some nasty bug in 2.5.1) and forgot to upgrade to release. Sorry for taking up your time and thank you for the quick response.

**Comment by travisghansen** [comment]
I actually meant the integration version but that also makes sense as the only other person to run into the issue was running a 2.6 pre release. Anyway glad it’s working!
