### ISSUE TITLE
Read timeout

### ISSUE THREAD

**Issue by ricktonoli** [travisghansen/hass-pfsense#98]
I seem to be getting a similar read timeout with the 2022.8 update (worked before that). 

2022-08-13 18:32:10.680 ERROR (MainThread) [custom_components.pfsense] Unexpected error fetching Tonoli pfSense state data: The read operation timed out
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/pfsense/__init__.py", line 96, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense/__init__.py", line 96, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
  File "/config/custom_components/pfsense/__init__.py", line 339, in update
    self._state["dhcp_leases"] = self._get_dhcp_leases()
  File "/config/custom_components/pfsense/__init__.py", line 229, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/pfsense/__init__.py", line 288, in _get_dhcp_leases
    return self._client.get_dhcp_leases()
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 665, in get_dhcp_leases
    response = self._exec_php(script)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 63, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 96, in _exec_php
    response = self._get_proxy().pfsense.exec_php(script)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1179, in single_request
    resp = http_conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

**Comment by travisghansen** [comment]
Is the behavior erratic? Are those failure responses simply happening 1 out 5 or 10 tries or something similar?

**Comment by nathanmay** [comment]
I appear to be getting the same since updating HA to 2022.8 - At first I thought it was something I did as have been tinkering with my home network (including updating HA)....I have then stumbled across this post, it has been working perfectly for months before this.

I have now lost all access to pfsense via the pfsense integration. And it just shows the below...

![image](https://user-images.githubusercontent.com/33894037/184707889-0cd471ec-6b74-4d53-995f-2c536f5cf35a.png)


```
This error originated from a custom integration.

Logger: custom_components.pfsense
Source: custom_components/pfsense/pypfsense/__init__.py:96
Integration: pfSense (documentation, issues)
First occurred: 8:47:38 PM (4 occurrences)
Last logged: 8:49:20 PM

Unexpected error fetching pfsense pfSense state data: The read operation timed out
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/pfsense/__init__.py", line 96, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense/__init__.py", line 96, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
  File "/config/custom_components/pfsense/__init__.py", line 339, in update
    self._state["dhcp_leases"] = self._get_dhcp_leases()
  File "/config/custom_components/pfsense/__init__.py", line 229, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/pfsense/__init__.py", line 288, in _get_dhcp_leases
    return self._client.get_dhcp_leases()
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 665, in get_dhcp_leases
    response = self._exec_php(script)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 63, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 96, in _exec_php
    response = self._get_proxy().pfsense.exec_php(script)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1179, in single_request
    resp = http_conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
```

**Comment by travisghansen** [comment]
Does it always fail on the `get_dhcp_leases` process, or does the error sometimes have something else roughly where that method is invoked?

**Comment by nathanmay** [comment]
> Does it always fail on the `get_dhcp_leases` process, or does the error sometimes have something else roughly where that method is invoked?

I've just look at the most recent occurrence of this error and yes stuck on the same bit again `get_dhcp_leases`

I'll keep monitoring it throughout tomorrow to see what happens.

**Comment by ricktonoli** [comment]
Didn't see that before, is probably related to the really long time it's taking to load dhcp leases in the pfSense itself, I noticed suddenly it's taking a good 10-20 seconds to load my leases page. Problem might be on the pfSense side in that case.

@nathanmay in the pfSense browser, does it take really long to load Status > DHCP Leases for you as well?

**Comment by travisghansen** [comment]
It’s pretty easy to replicate from the console/cli what the integration does if you want to give that a try as well.

**Comment by nathanmay** [comment]
> Didn't see that before, is probably related to the really long time it's taking to load dhcp leases in the pfSense itself, I noticed suddenly it's taking a good 10-20 seconds to load my leases page. Problem might be on the pfSense side in that case.
> 
> @nathanmay in the pfSense browser, does it take really long to load Status > DHCP Leases for you as well?
> 
> Might be related: https://www.reddit.com/r/PFSENSE/comments/no64lv/very_slow_opening_of_statusdhcp_leases_page/. Going to try some of the suggestions here to see if it speeds up the DHCP Leases page and potentially fixes this issue as well.

I hadn't noticed that however I've loaded my DHCP leases pages up several times this morning to test and on average takes 42 seconds to load via the GUI (workstation on wired LAN

I wonder if this has had some bearing on what is happening here.


I am going to try a fresh install in my dev environment later and see if a new install also loads slowly on DHCP pages and then will link this component and see what result I get. 

However is definitely strange as my setup was working fine a week ago!

**Comment by ricktonoli** [comment]
Looks like that was the problem for me, after I cleared all the DHCP leases in pfSense (Clear all DHCP leases button at the bottom of the Status > DHCP Leases page) the page loaded snappy fast and the integration started working again.

**Comment by nathanmay** [comment]
> Looks like that was the problem for me, after I cleared all the DHCP leases in pfSense (Clear all DHCP leases button at the bottom of the Status > DHCP Leases page) the page loaded snappy fast and the integration started working again.

@ricktonoli thanks for this, I'm at work at the minute but once I'm home I'll give this a try on my system. Hopefully it is as simple as this, and simply one of those weird querks! 

@travisghansen I'll let you know how I get on later!

**Comment by travisghansen** [comment]
Sounds good. We may be able to dig in even deeper and see if it’s a specific entry if you’d like before clearing it. I’ll dig through the pfsense code to see the exact commands they are executing and send them over and maybe we’ll be able to glean something from trying those manually before clearing the table.

**Comment by travisghansen** [comment]
OK, so the relevant code is found here: https://github.com/pfsense/pfsense/blob/master/src/etc/inc/system.inc#L675-L885

Reading the code over the basics are it reads the `/var/dhcpd/var/db/dhcpd.leases` file and parses it. Then try to enrich the data a bit including in certain circumstances doing a reverse lookup of the ip trying to map it back to a hostname. If I had to venture a guess it seems to me the most likely candidate for being time consuming is the hostname lookup process/DNS.

Looking through my code it appears that the hostnames are not used at all and so I can explicitly tell that process to not try and do lookups (the method allows you to send that in as a parameter). Additionally, this dhcp data is generally not something that changes frequently so I could potentially 'background' the lookup of the data and simply use the most recently fetched data (I do this same thing with the firmware/system update checks as that api call can sometimes take a bit of time as well).

**Comment by travisghansen** [comment]
I've released `v0.5.8`, maybe give that a try before resetting your leases just to see if it helps.

https://github.com/travisghansen/hass-pfsense/commit/3bae5882231043065114b6526ac755c59774bd7b

**Comment by nathanmay** [comment]
Unfortunately I didn't check Github notifications before clearing all my leases....

However I can now confirm that clearing all my DHCP leases has **_fixed the issue_** between HA/Component 
& pfsense.

Fantastic work @travisghansen, such a great component!

**Comment by travisghansen** [comment]
Well, at a minimum we’ve made some minor improvements! :) if we run into the issue in the future we can look into the backgrounded route as well.
